package co.jp.api.cmn;

import java.util.List;

public class Constants {

	public static String SPACE = "";
	
	public static String ID = "id";
	public static String STT = "STT";
	public static String NAME = "Name";
	public static String START_DATE = "startDate";
	public static String END_DATE = "endDate";
	public static String STATUS = "status";
	public static String DATA = "data";
	public static String DATA_LIST = "dataList";
	public static String SHEET_NAME = "sheetName";
	public static String DISPLAY_ORDER = "displayOrder";
	public static String EXCEL_XLS = "xls";
	public static String EXCEL_XLSX = "xlsx";
	public static String MESSAGE_FIELD_EMPTY = "Field is Emty";

	// Config file name
	public static final String RESOURCE_PRODUCT_EXCEL = "classpath:/config/excel/product-excel-config.json";
	public static final long EXPIRE_TOKEN_AFTER_HOURS = 1;

	/** Msg*/
	public static final String MSG_I00001 = "Change password success";
	public static final String MSG_I00002 = "Change password failse";
	public static final String MSG_I00003 = "Code out of date";

	public static int NUMBER_0 = 0;
	public static int NUMBER_1 = 1;
	public static int NUMBER_2 = 2;
	public static int NUMBER_3 = 3;
	public static int NUMBER_4 = 4;
	public static int NUMBER_5 = 5;
	public static int NUMBER_6 = 6;
	public static int NUMBER_7 = 7;
	public static int NUMBER_8 = 8;
	public static int NUMBER_9 = 9;
	public static int NUMBER_10 = 10;
	public static int NUMBER_11 = 11;
	public static int NUMBER_12 = 12;
	public static int NUMBER_13 = 13;
	public static int NUMBER_14 = 14;
	public static int NUMBER_15 = 15;
	public static int NUMBER_16 = 16;
	public static int NUMBER_17 = 17;
	public static int NUMBER_18 = 18;
	public static int NUMBER_19 = 19;
	public static int NUMBER_20 = 20;
	public static int NUMBER_21 = 21;
	public static int NUMBER_22 = 22;
	public static int NUMBER_23 = 23;
	public static int NUMBER_24 = 24;
	public static int NUMBER_25 = 25;
	public static int NUMBER_26 = 26;
	public static int NUMBER_27 = 27;
	public static int NUMBER_28 = 28;
	public static int NUMBER_29 = 29;
	public static int NUMBER_30 = 30;
	public static int NUMBER_31 = 31;
	public static int NUMBER_32 = 32;
	public static int NUMBER_33 = 33;
	public static int NUMBER_34 = 34;
	public static int NUMBER_35 = 35;
	public static int NUMBER_36 = 36;
	public static int NUMBER_37 = 37;
	public static int NUMBER_38 = 38;
	public static int NUMBER_39 = 39;
	public static int NUMBER_40 = 40;
	public static int NUMBER_41 = 41;
	public static int NUMBER_42 = 42;
	public static int NUMBER_43 = 43;
	public static int NUMBER_44 = 44;
	public static int NUMBER_45 = 45;
	public static int NUMBER_46 = 46;
	public static int NUMBER_47 = 47;
	public static int NUMBER_48 = 48;
	public static int NUMBER_49 = 49;
	public static int NUMBER_50 = 50;
	public static int NUMBER_51 = 51;
	public static int NUMBER_52 = 52;
	public static int NUMBER_53 = 53;
	public static int NUMBER_54 = 54;
	public static int NUMBER_55 = 55;
	public static int NUMBER_56 = 56;
	public static int NUMBER_57 = 57;
	public static int NUMBER_58 = 58;
	public static int NUMBER_59 = 59;
	public static int NUMBER_60 = 60;
	public static int NUMBER_61 = 61;
	public static int NUMBER_62 = 62;
	public static int NUMBER_63 = 63;
	public static int NUMBER_64 = 64;
	public static int NUMBER_65 = 65;
	public static int NUMBER_66 = 66;
	public static int NUMBER_67 = 67;
	public static int NUMBER_68 = 68;
	public static int NUMBER_69 = 69;
	public static int NUMBER_70 = 70;
	public static int NUMBER_71 = 71;
	public static int NUMBER_72 = 72;
	public static int NUMBER_73 = 73;
	public static int NUMBER_74 = 74;
	public static int NUMBER_75 = 75;
	public static int NUMBER_76 = 76;
	public static int NUMBER_77 = 77;
	public static int NUMBER_78 = 78;
	public static int NUMBER_79 = 79;
	public static int NUMBER_80 = 80;
	public static int NUMBER_81 = 81;
	public static int NUMBER_82 = 82;
	public static int NUMBER_83 = 83;
	public static int NUMBER_84 = 84;
	public static int NUMBER_85 = 85;
	public static int NUMBER_86 = 86;
	public static int NUMBER_87 = 87;
	public static int NUMBER_88 = 88;
	public static int NUMBER_89 = 89;
	public static int NUMBER_90 = 90;
	public static int NUMBER_91 = 91;
	public static int NUMBER_92 = 92;
	public static int NUMBER_93 = 93;
	public static int NUMBER_94 = 94;
	public static int NUMBER_95 = 95;
	public static int NUMBER_96 = 96;
	public static int NUMBER_97 = 97;
	public static int NUMBER_98 = 98;
	public static int NUMBER_99 = 99;
	public static int NUMBER_100 = 100;
	public static int NUMBER_200 = 200;
	public static int NUMBER_400 = 400;

}
